import React from "react";

export default function PrivacyPolicy() {
  return (
    <div className="max-w-5xl mx-auto p-6">
      <h1 className="text-3xl font-bold mb-6">Privacy Policy</h1>

      <p className="mb-4">
        <strong>Effective Date:</strong> 12/16/2024
      </p>

      <section className="mb-8">
        <h2 className="text-2xl font-semibold mb-4">Introduction</h2>
        <p>
          At resumach, we are committed to protecting your privacy. This Privacy Policy outlines how we collect, use, and protect your information when you use our services.
        </p>
      </section>

      <section className="mb-8">
        <h2 className="text-2xl font-semibold mb-4">Information We Collect</h2>
        <p>
          We collect the following types of information when you use resumach:
        </p>
        <ul className="list-disc ml-6">
          <li>Personal information included in your resume, such as name, email, and phone number.</li>
          <li>Uploaded resumes and tailored versions generated by our service.</li>
        </ul>
      </section>

      <section className="mb-8">
        <h2 className="text-2xl font-semibold mb-4">How We Use Your Information</h2>
        <ul className="list-disc ml-6">
          <li>To send your data to the OpenAI's GPT-4o API for tailoring your resume.</li>
          <li>To store your uploaded and tailored resumes in our database.</li>
          <li>To process payments securely using Stripe for our Pro tier services.</li>
        </ul>
      </section>

      <section className="mb-8">
        <h2 className="text-2xl font-semibold mb-4">How We Protect Your Information</h2>
        <p>
          We use industry-standard security measures to protect your data, including encryption and secure access protocols.
        </p>
      </section>

      <section className="mb-8">
        <h2 className="text-2xl font-semibold mb-4">Your Rights</h2>
        <p>
          You have the right to access, modify, or delete your personal information. Please contact us at info@ajalloh.com to make such requests.
        </p>
      </section>

      <section className="mb-8">
        <h2 className="text-2xl font-semibold mb-4">Changes to This Policy</h2>
        <p>
          We may update this Privacy Policy from time to time. Any changes will be posted on this page with an updated effective date.
        </p>
      </section>

      <section className="mb-8">
        <h2 className="text-2xl font-semibold mb-4">Contact Us</h2>
        <p>
          If you have any questions or concerns about this Privacy Policy, please contact us:
        </p>
        <ul className="list-disc ml-6">
          <li>Email: info@ajalloh.com</li>
        </ul>
      </section>

      <p className="text-sm text-gray-500">
        Thank you for trusting resumach to assist you in your job search.
      </p>
    </div>
  );
};
