export interface User {
  id: string; // uuid
  email: string; // character varying
};

export interface ResumeSchema {
  id: bigint;
  created_at: Date; // timestamp with time zone
  first_name: string; // text
  middle_name?: string | null; // text
  last_name: string; // text
  mobile?: string | null; // character varying
  email: string; // character varying
  linkedin?: string | null; // character varying
  x_twitter?: string | null; // character varying
  github?: string | null; // character varying
  dribbble?: string | null; // character varying
  facebook?: string | null; // character varying
  website?: string | null; // character varying
  summary?: string | null; // text
  user_id: User;
  education_id: EducationSchema[]; 
  employment_id: EmploymentSchema[]; 
  skill_id: SkillSchema[];
  project_id: ProjectSchema[]; 
  award_id: AwardSchema[]; 
  certification_id: CertificationSchema[];
  volunteering_id: VolunteeringSchema[];
  publication_id: PublicationSchema[];
  reference_id: ReferenceSchema[];
};

export interface EducationSchema {
  degree?: string | null; // character varying, null
  institution?: string | null; // character varying, null
  city?: string | null; // text, null
  state?: string | null; // text, null
  country?: string | null; // text, null
  start_date?: Date | null; // date, null
  end_date?: Date | null; // date, null
  additional_info?: string | null; // text, null
  updated_at?: Date | null; // timestamp without time zone, null, default now()
};
export interface EmploymentSchema {
  title?: string | null; // text, null
  company?: string | null; // text, null
  city?: string | null; // text, null
  state?: string | null; // text, null
  country?: string | null; // text, null
  job_description?: string | null; // text, null
  start_date?: Date | null; // date, null
  end_date?: Date | null; // date, null
  updated_at?: Date | null; // timestamp without time zone, null, default now()
}

export interface ProjectSchema {
  title?: string | null; // text, null
  description?: string | null; // text, null
  url?: string | null; // character varying, null
  start_date?: Date | null; // date, null
  end_date?: Date | null; // date, null
  updated_at?: Date | null; // timestamp without time zone, null, default now()
};

export interface SkillSchema {
  category?: string | null; // text, null
  skills?: string | null; // text, null
  updated_at?: Date | null; // timestamp without time zone, null, default now()
};

export interface AwardSchema {
  title?: string | null; // text, null
  awarder?: string | null; // text, null
  date?: string | null; // character varying, null
  website?: string | null; // character varying, null
  summary?: string | null; // text, null
  updated_at?: Date | null; // timestamp without time zone, null, default now()
};

export interface CertificationSchema {
  name?: string | null; // text, null
  issuer?: string | null; // text, null
  date?: string | null; // character varying, null
  updated_at?: Date | null; // timestamp without time zone, null, default now()
  website?: string | null; // character varying, null
  summary?: string | null; // text, null
};

export interface PublicationSchema {
  name?: string | null; // text, null
  publisher?: string | null; // text, null
  date?: string | null; // character varying, null
  website?: string | null; // character varying, null
  summary?: string | null; // text, null
  updated_at?: Date | null; // timestamp without time zone, null, default now()
};

export type VolunteeringSchema = {
  organization?: string | null; // text, null
  position?: string | null; // text, null
  location?: string | null; // text, null
  date_range?: string | null; // character varying, null
  website?: string | null; // character varying, null
  summary?: string | null; // text, null
  updated_at?: Date | null; // timestamp without time zone, null, default now()
};

export interface ReferenceSchema {
  name?: string | null; // text, null
  email?: string | null; // character varying, null
  website?: string | null; // character varying, null
  summary?: string | null; // text, null
  updated_at?: Date | null; // timestamp without time zone, null, default now()
};

export interface ResumeFileSchema {
  id: bigint; // generated by default as identity, not null
  filename?: string | null; // character varying, null
  file_url: string; // character varying, not null
  user_id: User;
  updated_at?: Date | null; // timestamp without time zone, null, default now()
};

export type FilterKeys<T, Condition> = {
  [Key in keyof T]: T[Key] extends Condition ? Key : never;
}[keyof T];


export interface Session {
  id: string
  email: string
}